# Generated by Django 5.0.14 on 2026-09-16 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquiry',
            options={'ordering': ['-created_at', '-id'], 'verbose_name_plural': 'enquiries'},
        ),
    ]
