# Generated by Django 5.0.14 on 2026-09-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_published', models.BooleanField(default=True, help_text='Untick to hide from the site without deleting.')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_published', models.BooleanField(default=True, help_text='Untick to hide from the site without deleting.')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Used in /industries?industry=<slug>.', max_length=90, unique=True)),
                ('pitch', models.TextField()),
                ('features', models.TextField(help_text='One per line.')),
                ('theme', models.CharField(choices=[('restaurant', 'Restaurant'), ('corporate', 'Corporate'), ('education', 'Education'), ('travel', 'Travel'), ('retail', 'Retail'), ('realEstate', 'Real estate'), ('professional', 'Professional services'), ('local', 'Local business')], help_text='Which demo mockup to show.', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'industries',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_published', models.BooleanField(default=True, help_text='Untick to hide from the site without deleting.')),
                ('name', models.CharField(max_length=60)),
                ('tagline', models.CharField(max_length=160)),
                ('features', models.TextField(help_text='One per line.')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_published', models.BooleanField(default=True, help_text='Untick to hide from the site without deleting.')),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_published', models.BooleanField(default=True, help_text='Untick to hide from the site without deleting.')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_published', models.BooleanField(default=True, help_text='Untick to hide from the site without deleting.')),
                ('title', models.CharField(max_length=80)),
                ('category', models.CharField(help_text='e.g. "E-commerce website".', max_length=80)),
                ('description', models.TextField()),
                ('features', models.TextField(help_text='One per line.')),
                ('theme', models.CharField(choices=[('restaurant', 'Restaurant'), ('corporate', 'Corporate'), ('education', 'Education'), ('travel', 'Travel'), ('retail', 'Retail'), ('realEstate', 'Real estate'), ('professional', 'Professional services'), ('local', 'Local business')], max_length=20)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ORIK Webcraft', max_length=80)),
                ('description', models.TextField(help_text='Used in the footer and as the site meta description.')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'site settings',
                'verbose_name_plural': 'site settings',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_published', models.BooleanField(default=True, help_text='Untick to hide from the site without deleting.')),
                ('platform', models.CharField(choices=[('twitter', 'Twitter'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn'), ('medium', 'Medium')], max_length=20, unique=True)),
                ('label', models.CharField(max_length=40)),
                ('href', models.URLField(blank=True, help_text='Leave blank until the profile exists; blank links are hidden.')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_published', models.BooleanField(default=True, help_text='Untick to hide from the site without deleting.')),
                ('value', models.CharField(help_text='Shown large, e.g. "10+" or "24/7".', max_length=16)),
                ('label', models.CharField(max_length=80)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_published', models.BooleanField(default=True, help_text='Untick to hide from the site without deleting.')),
                ('quote', models.TextField()),
                ('name', models.CharField(max_length=80)),
                ('business', models.CharField(max_length=80)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
