# Generated by Django 5.0.14 on 2026-09-17 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_published', models.BooleanField(default=True, help_text='Untick to hide from the site without deleting.')),
                ('name', models.CharField(max_length=80)),
                ('role', models.CharField(help_text='Job title, e.g. "Founder" or "Designer".', max_length=80)),
                ('bio', models.TextField(blank=True, help_text='Optional one or two lines shown under the role.')),
                ('photo', models.ImageField(blank=True, help_text='Portrait. Leave blank to show initials instead.', upload_to='team/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('whatsapp', models.CharField(blank=True, help_text='Number in international format, e.g. +9779800000000.', max_length=40)),
                ('linkedin', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
