# Generated by Django 5.0.14 on 2026-09-23 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=160)),
                ('subheading', models.TextField()),
                ('qualities_label', models.CharField(default='Every ORIK website is:', help_text='Small label on the card under the paragraph.', max_length=60)),
                ('qualities', models.TextField(default='Mobile\nFast\nModern', help_text='One per line. Three short words fit the card best.')),
                ('image', models.ImageField(blank=True, help_text='Showcase image. Leave blank to keep the built-in one.', upload_to='hero/')),
                ('image_alt', models.CharField(blank=True, help_text='Describes the image for screen readers. Required if you upload one.', max_length=160)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'hero section',
                'verbose_name_plural': 'hero section',
            },
        ),
        migrations.CreateModel(
            name='HeroBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_published', models.BooleanField(default=True, help_text='Untick to hide from the site without deleting.')),
                ('label', models.CharField(max_length=40)),
                ('icon', models.CharField(choices=[('enquiries', 'Rising enquiries'), ('whatsapp', 'WhatsApp'), ('mobile', 'Mobile'), ('seo', 'Search / SEO'), ('speed', 'Speed'), ('target', 'Target')], default='enquiries', max_length=20)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='content.herosection')),
            ],
            options={
                'verbose_name': 'hero badge',
                'verbose_name_plural': 'hero badges',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
