# Generated by Django 5.0.14 on 2026-09-23 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_herosection_herobadge'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourIdeaSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField(help_text='Line breaks are kept on wide screens.')),
                ('closing_text', models.TextField(help_text='The line under the cards.')),
                ('cta_label', models.CharField(default='Get a free consultation', max_length=60)),
                ('cta_href', models.CharField(default='/contact', help_text='A path such as "/contact".', max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'your idea',
                'verbose_name_plural': 'your idea',
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Set automatically; cards are edited inside the section.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='content.yourideasection'),
        ),
    ]
