# Generated by Django 5.0.14 on 2026-09-23 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_yourideasection_problem_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalExperiencesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField(help_text='Line breaks are kept on wide screens.')),
                ('link_label', models.CharField(default='Get a free consultation', max_length=60)),
                ('link_href', models.CharField(default='/contact', help_text='A path such as "/contact".', max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'digital experiences',
                'verbose_name_plural': 'digital experiences',
            },
        ),
        migrations.AddField(
            model_name='stat',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Set automatically; stats are edited inside the section.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='content.digitalexperiencessection'),
        ),
    ]
