# Generated by Django 5.0.14 on 2026-09-24 12:12

import django.db.models.deletion
from django.db import migrations, models

# The eight demo sites that used to live in frontend/src/data/home.ts, keyed by
# the value the old `theme` column held.
TEMPLATES = [
    ("restaurant", "Saffron Table", "saffrontable.demo", "Fresh flavours, served daily",
     "Book a table or order online in seconds.", "Book a table",
     ["Menu", "Book", "Contact"], ["Breakfast", "Lunch", "Dinner"]),
    ("corporate", "Summit Group", "summitgroup.demo", "Business solutions that scale",
     "Consulting and services for growing companies.", "Talk to us",
     ["About", "Services", "Careers"], ["Strategy", "Operations", "Support"]),
    ("education", "BrightPath Education", "brightpath.demo", "Study abroad with confidence",
     "Guidance for courses, visas and applications.", "Book a consultation",
     ["Courses", "Countries", "Contact"], ["Australia", "UK", "Canada"]),
    ("travel", "Horizon Trails", "horizontrails.demo", "Plan your next adventure",
     "Guided tours, treks and holidays made simple.", "Explore tours",
     ["Tours", "Destinations", "Contact"], ["Trekking", "City tours", "Adventure"]),
    ("retail", "Urban Thread", "urbanthread.demo", "New season, new styles",
     "Shop the latest collection online.", "Shop now",
     ["Women", "Men", "Sale"], ["Jackets", "Dresses", "Sneakers"]),
    ("realEstate", "Keystone Realty", "keystonerealty.demo", "Find the home that fits your life",
     "Apartments, houses and land in great locations.", "View listings",
     ["Buy", "Rent", "Agents"], ["Apartments", "Houses", "Land"]),
    ("professional", "Clarity Advisors", "clarityadvisors.demo", "Expert advice you can rely on",
     "Accounting, tax and legal support for small businesses.", "Schedule a call",
     ["Services", "Team", "Insights"], ["Accounting", "Tax", "Legal"]),
    ("local", "Corner Bakery", "cornerbakery.demo", "Baked fresh every morning",
     "Cakes, breads and coffee just around the corner.", "Order now",
     ["Menu", "Offers", "Visit"], ["Cakes", "Breads", "Coffee"]),
]


def create_templates(apps, schema_editor):
    """Build the library, then point each industry and project at its old theme."""
    Template = apps.get_model("content", "Template")
    Industry = apps.get_model("content", "Industry")
    Project = apps.get_model("content", "Project")

    by_key = {}
    for index, (key, name, domain, headline, subline, cta, nav, cards) in enumerate(TEMPLATES):
        by_key[key] = Template.objects.create(
            key=key, name=name, domain=domain, headline=headline, subline=subline,
            cta=cta, nav="\n".join(nav), cards="\n".join(cards), order=index,
        )

    for industry in Industry.objects.all():
        industry.template_industry = by_key.get(industry.theme)
        industry.save(update_fields=["template_industry"])

    for project in Project.objects.all():
        project.template_project = by_key.get(project.theme)
        project.save(update_fields=["template_project"])


def unlink_templates(apps, schema_editor):
    apps.get_model("content", "Template").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_digitalexperiencessection_stat_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustriesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Built for businesses like yours.', max_length=120)),
                ('link_label', models.CharField(default='Start a project', max_length=60)),
                ('link_href', models.CharField(default='/contact', max_length=120)),
                ('footnote_label', models.CharField(default='Every demo we build is', max_length=80)),
                ('footnote_items', models.TextField(default='Mobile friendly\nFast & modern\nBusiness focused', help_text='One per line; joined with a dot on the site.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'industries section',
                'verbose_name_plural': 'industries section',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_published', models.BooleanField(default=True, help_text='Untick to hide from the site without deleting.')),
                ('key', models.SlugField(help_text='Short internal id, e.g. restaurant. Used to match the built-in designs.', max_length=40, unique=True)),
                ('name', models.CharField(help_text='The demo business name, e.g. "Saffron Table".', max_length=60)),
                ('domain', models.CharField(help_text='e.g. "saffrontable.demo".', max_length=80)),
                ('headline', models.CharField(help_text='The big line, e.g. "Fresh flavours, served daily".', max_length=120)),
                ('subline', models.CharField(help_text='The line under the headline.', max_length=200)),
                ('cta', models.CharField(help_text='Button label, e.g. "Book a table".', max_length=40)),
                ('nav', models.TextField(help_text='Nav links, one per line. Three fit best.')),
                ('cards', models.TextField(help_text='Card labels, one per line. Three fit best.')),
                ('accent', models.CharField(default='#008454', help_text='Hex colour, e.g. #008454.', max_length=9)),
                ('accent_dark', models.CharField(default='#00683e', max_length=9)),
                ('soft', models.CharField(default='#f0f8f5', max_length=9)),
            ],
            options={
                'verbose_name': 'template',
                'verbose_name_plural': 'templates',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        # Order matters: add the links, copy the old theme keys across while the
        # `theme` column still exists, and only then drop it.
        migrations.AddField(
            model_name='industry',
            name='template_industry',
            field=models.ForeignKey(blank=True, help_text='Which demo mockup to show in the preview.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='industries', to='content.template', verbose_name='template'),
        ),
        migrations.AddField(
            model_name='project',
            name='template_project',
            field=models.ForeignKey(blank=True, help_text='Which demo mockup to show in the preview.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='content.template', verbose_name='template'),
        ),
        migrations.RunPython(create_templates, unlink_templates),
        migrations.RemoveField(
            model_name='industry',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='project',
            name='theme',
        ),
    ]
